apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Contoh Web di Kubernetes LER</title>
        <style>
            body { font-family: Arial; text-align: center; margin-top: 50px; }
        </style>
    </head>
    <body>
        <h1><b>Selamat Datang!</b></h1>
        <h2>Anda sedang melihat halaman web yang di-deploy di Kubernetes PELER.</h2>
        <p>Ini adalah halaman web statis yang di-deploy di Kubernetes.</p>
    </body>
    </html>